/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dadinhos;

/**
 *
 * @author talita
 */
public class Dadinho extends javax.swing.JFrame {
    
     Integer Vitoria1 = 0, Vitoria2 = 0;
     
    
    /**
     * Creates new form Dadinho
     */
    public Dadinho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSortear = new javax.swing.JButton();
        lblDado1 = new javax.swing.JLabel();
        lblDado2 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        lblVitoria1 = new javax.swing.JLabel();
        lblVitoria2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSortear.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSortear.setText("SORTEAR DADINHOS");
        btnSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortearActionPerformed(evt);
            }
        });

        lblDado1.setText("Dado 1:");

        lblDado2.setText("Dado 2:");

        lblResultado.setText("Resultado final:");

        lblVitoria1.setText("Vitoria 1°");

        lblVitoria2.setText("Vitoria 2°");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResultado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVitoria1)
                            .addComponent(lblVitoria2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnSortear))
                            .addComponent(lblDado2))
                        .addGap(0, 88, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnSortear)))
                .addGap(13, 13, 13)
                .addComponent(lblDado2)
                .addGap(32, 32, 32)
                .addComponent(lblResultado)
                .addGap(31, 31, 31)
                .addComponent(lblVitoria1)
                .addGap(31, 31, 31)
                .addComponent(lblVitoria2)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortearActionPerformed
         Double sorteio1 = Math.ceil((Math.random()*((6-1)+1)));
        
        lblDado1.setText("Dado 1: " + sorteio1.toString());
        
        Double sorteio2 = Math.ceil((Math.random()*((6-1)+1)));
        lblDado2.setText("Dado 2: " + sorteio2.toString());
        
        
        if(sorteio1 > sorteio2){
        Vitoria1 ++;
        lblVitoria1.setText("Vitoria 1: " + Vitoria1.toString());
        lblResultado.setText("Dado 1 Vencedor");
        }else if(sorteio2 > sorteio1){
        Vitoria2 ++;
        lblVitoria2.setText("Vitoria 2: " + Vitoria2.toString());
        lblResultado.setText("Dado 2 Vencedor");
        }else{
        lblResultado.setText("Empate");
        }
          
    }//GEN-LAST:event_btnSortearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dadinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         //</editor-fold>
         
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dadinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSortear;
    private javax.swing.JLabel lblDado1;
    private javax.swing.JLabel lblDado2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblVitoria1;
    private javax.swing.JLabel lblVitoria2;
    // End of variables declaration//GEN-END:variables

}