/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lista08.resolucao;

/**
 *
 * @author talita
 */
public class Elevadores extends javax.swing.JFrame {
    Elevador elevador1 = new Elevador();
    Elevador elevador2 = new Elevador();
    Elevador elevador3 = new Elevador();
    /**
     * Creates new form Elevadores
     */
    public Elevadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnMulher3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblTotalPessoas2 = new javax.swing.JLabel();
        lblTotalPessoas1 = new javax.swing.JLabel();
        btnCrianca3 = new javax.swing.JButton();
        lblTotalPessoas3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotalPeso1 = new javax.swing.JLabel();
        btnHomem1 = new javax.swing.JButton();
        btnMulher1 = new javax.swing.JButton();
        lblTotalPeso3 = new javax.swing.JLabel();
        lblTotalPeso2 = new javax.swing.JLabel();
        btnHomem2 = new javax.swing.JButton();
        btnCrianca2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCrianca1 = new javax.swing.JButton();
        btnHomem3 = new javax.swing.JButton();
        btnMulher2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Peso total no elevador:");

        btnMulher3.setText("Mulher");
        btnMulher3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulher3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Peso total no elevador:");

        lblTotalPessoas2.setText("0");

        lblTotalPessoas1.setText("0");

        btnCrianca3.setText("Criança");
        btnCrianca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrianca3ActionPerformed(evt);
            }
        });

        lblTotalPessoas3.setText("0");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elevador 1");

        jLabel4.setText("Total passageiros no elevador:");

        jLabel5.setText("Total passageiros no elevador:");

        jLabel8.setText("Total passageiros no elevador:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Elevador 3");

        lblTotalPeso1.setText("0");

        btnHomem1.setText("Homem");
        btnHomem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomem1ActionPerformed(evt);
            }
        });

        btnMulher1.setText("Mulher");
        btnMulher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulher1ActionPerformed(evt);
            }
        });

        lblTotalPeso3.setText("0");

        lblTotalPeso2.setText("0");

        btnHomem2.setText("Homem");
        btnHomem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomem2ActionPerformed(evt);
            }
        });

        btnCrianca2.setText("Criança");
        btnCrianca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrianca2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Elevador 2");

        btnCrianca1.setText("Criança");
        btnCrianca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrianca1ActionPerformed(evt);
            }
        });

        btnHomem3.setText("Homem");
        btnHomem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomem3ActionPerformed(evt);
            }
        });

        btnMulher2.setText("Mulher");
        btnMulher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulher2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Peso total no elevador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnHomem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMulher1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrianca1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPeso1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPessoas1)))))
                .addGap(0, 109, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalPessoas2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHomem2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnMulher2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCrianca2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalPeso2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHomem3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnMulher3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCrianca3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalPessoas3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalPeso3)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomem1)
                    .addComponent(btnMulher1)
                    .addComponent(btnCrianca1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotalPessoas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalPeso1))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomem2)
                    .addComponent(btnMulher2)
                    .addComponent(btnCrianca2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotalPessoas2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotalPeso2))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomem3)
                    .addComponent(btnMulher3)
                    .addComponent(btnCrianca3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTotalPessoas3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTotalPeso3))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMulher3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulher3ActionPerformed
        elevador3.entrarMulher();
        lblTotalPeso3.setText(elevador3.getPeso().toString());
        lblTotalPessoas3.setText(elevador3.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnMulher3ActionPerformed

    private void btnCrianca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrianca3ActionPerformed
        elevador3.entrarCrianca();
        lblTotalPeso3.setText(elevador3.getPeso().toString());
        lblTotalPessoas3.setText(elevador3.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnCrianca3ActionPerformed

    private void btnHomem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomem1ActionPerformed
        elevador1.entrarHomem();
        lblTotalPeso1.setText(elevador1.getPeso().toString());
        lblTotalPessoas1.setText(elevador1.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnHomem1ActionPerformed

    private void btnMulher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulher1ActionPerformed
        elevador1.entrarMulher();
        lblTotalPeso1.setText(elevador1.getPeso().toString());
        lblTotalPessoas1.setText(elevador1.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnMulher1ActionPerformed

    private void btnHomem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomem2ActionPerformed
        elevador2.entrarHomem();
        lblTotalPeso2.setText(elevador2.getPeso().toString());
        lblTotalPessoas2.setText(elevador2.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnHomem2ActionPerformed

    private void btnCrianca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrianca2ActionPerformed
        elevador2.entrarCrianca();
        lblTotalPeso2.setText(elevador2.getPeso().toString());
        lblTotalPessoas2.setText(elevador2.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnCrianca2ActionPerformed

    private void btnCrianca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrianca1ActionPerformed
        elevador1.entrarCrianca();
        lblTotalPeso1.setText(elevador1.getPeso().toString());
        lblTotalPessoas1.setText(elevador1.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnCrianca1ActionPerformed

    private void btnHomem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomem3ActionPerformed
        elevador3.entrarHomem();
        lblTotalPeso3.setText(elevador3.getPeso().toString());
        lblTotalPessoas3.setText(elevador3.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnHomem3ActionPerformed

    private void btnMulher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulher2ActionPerformed
        elevador2.entrarMulher();
        lblTotalPeso2.setText(elevador2.getPeso().toString());
        lblTotalPessoas2.setText(elevador2.getTotalPassageiros().toString());
    }//GEN-LAST:event_btnMulher2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elevadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elevadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrianca1;
    private javax.swing.JButton btnCrianca2;
    private javax.swing.JButton btnCrianca3;
    private javax.swing.JButton btnHomem1;
    private javax.swing.JButton btnHomem2;
    private javax.swing.JButton btnHomem3;
    private javax.swing.JButton btnMulher1;
    private javax.swing.JButton btnMulher2;
    private javax.swing.JButton btnMulher3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblTotalPeso1;
    private javax.swing.JLabel lblTotalPeso2;
    private javax.swing.JLabel lblTotalPeso3;
    private javax.swing.JLabel lblTotalPessoas1;
    private javax.swing.JLabel lblTotalPessoas2;
    private javax.swing.JLabel lblTotalPessoas3;
    // End of variables declaration//GEN-END:variables
}
